"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { AdminSupporterPanel } from "@/components/v11/AdminSupporterPanel";
import { COMMUNITY_ROLE_OPTIONS, RoleBadges } from "@/components/v13/RoleBadges";
import type { CommunityRole, StaffRole } from "@/lib/chat-types";

type AdminUser={id:string;email:string;username:string;display_name:string;admin_tag:string|null;status_text:string;profile_emoji:string;last_active_at:string|null;created_at:string;last_sign_in_at:string|null;banned_until:string|null;is_admin:boolean;staff_role:StaffRole;community_roles:CommunityRole[];supporter:boolean;supporter_since:string|null;supporter_label:string;};
type Report={id:string;reporter_id:string;reported_user_id:string|null;message_id:string|null;reason:string;details:string;status:"open"|"resolved"|"dismissed";created_at:string;reviewed_at:string|null;reviewed_by:string|null;};
type Tab="accounts"|"reports"|"roles"|"support"|"owner";

async function adminFetch(url:string,options?:RequestInit){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Your session expired. Sign in again.");const response=await fetch(url,{...options,cache:"no-store",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(options?.headers??{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Staff request failed.");return body;}
function formatDate(value:string|null){if(!value)return"Never";const d=new Date(value);return Number.isNaN(d.getTime())?"Unknown":d.toLocaleString();}

export function ModerationCenter(){
 const router=useRouter();const[ready,setReady]=useState(false);const[userId,setUserId]=useState("");const[myRole,setMyRole]=useState<StaffRole>(null);const[tab,setTab]=useState<Tab>("accounts");const[query,setQuery]=useState("");const[users,setUsers]=useState<AdminUser[]>([]);const[reports,setReports]=useState<Report[]>([]);const[reportFilter,setReportFilter]=useState<"open"|"all"|"resolved"|"dismissed">("open");const[loadingUsers,setLoadingUsers]=useState(false);const[loadingReports,setLoadingReports]=useState(false);const[workingId,setWorkingId]=useState<string|null>(null);const[tag,setTag]=useState("OWNER");const[message,setMessage]=useState("");
 const isOwner=myRole==="owner",canAdmin=myRole==="owner"||myRole==="admin";
 useEffect(()=>{void(async()=>{const{data}=await supabase.auth.getUser();if(!data.user){router.replace("/");return;}const{data:role,error}=await supabase.rpc("my_staff_role");if(error||!["owner","admin","moderator"].includes(String(role))){router.replace("/chat");return;}setUserId(data.user.id);setMyRole(role as StaffRole);const{data:profile}=await supabase.from("profiles").select("admin_tag").eq("id",data.user.id).maybeSingle();setTag(String(profile?.admin_tag||"OWNER"));setReady(true);})();},[router]);
 const loadUsers=useCallback(async(search:string)=>{setLoadingUsers(true);setMessage("");try{const body=await adminFetch(`/api/admin/users?q=${encodeURIComponent(search.trim())}`);setUsers((body.users??[]) as AdminUser[]);}catch(e){setMessage(e instanceof Error?e.message:"Could not load users.");}finally{setLoadingUsers(false);}},[]);
 const loadReports=useCallback(async(filter:typeof reportFilter)=>{setLoadingReports(true);setMessage("");try{const body=await adminFetch(`/api/admin/reports?status=${encodeURIComponent(filter)}`);setReports((body.reports??[]) as Report[]);}catch(e){setMessage(e instanceof Error?e.message:"Could not load reports.");}finally{setLoadingReports(false);}},[]);
 useEffect(()=>{if(ready)void loadUsers("");},[ready,loadUsers]);useEffect(()=>{if(ready)void loadReports(reportFilter);},[ready,reportFilter,loadReports]);
 async function searchUsers(e?:FormEvent){e?.preventDefault();await loadUsers(query);}
 async function postUser(target:AdminUser,payload:Record<string,unknown>,success:string){setWorkingId(target.id);setMessage("");try{await adminFetch("/api/admin/users",{method:"POST",body:JSON.stringify({userId:target.id,...payload})});await loadUsers(query);setMessage(success);}catch(e){setMessage(e instanceof Error?e.message:"Could not update user.");}finally{setWorkingId(null);}}
 async function setBan(target:AdminUser,duration:"none"|"24h"|"168h"|"876000h"){if(duration==="876000h"&&!window.confirm(`Permanently ban @${target.username}?`))return;await postUser(target,{banDuration:duration},duration==="none"?`@${target.username} restored.`:`@${target.username} suspension updated.`);}
 async function toggleSupporter(target:AdminUser){await postUser(target,{supporterAction:target.supporter?"remove":"grant",supporterLabel:target.supporter_label||"SUPPORTER"},target.supporter?`Supporter removed from @${target.username}.`:`Supporter granted to @${target.username}.`);}
 async function setStaffRole(target:AdminUser,role:"none"|"admin"|"moderator"){await postUser(target,{staffRole:role},role==="none"?`@${target.username} is no longer staff.`:`@${target.username} is now ${role}.`);}
 async function toggleCommunityRole(target:AdminUser,role:CommunityRole){const has=target.community_roles.includes(role);await postUser(target,{communityRole:role,communityAction:has?"remove":"grant"},`${has?"Removed":"Granted"} ${role.replaceAll("_"," ")} ${has?"from":"to"} @${target.username}.`);}
 async function updateReport(reportId:string,status:"open"|"resolved"|"dismissed"){setWorkingId(reportId);try{await adminFetch("/api/admin/reports",{method:"POST",body:JSON.stringify({reportId,status})});await loadReports(reportFilter);setMessage(`Report marked ${status}.`);}catch(e){setMessage(e instanceof Error?e.message:"Could not update report.");}finally{setWorkingId(null);}}
 async function saveTag(){const clean=tag.trim();if(!/^[A-Za-z0-9 _-]{1,16}$/.test(clean)){setMessage("Owner tag must be 1–16 characters.");return;}const{error}=await supabase.rpc("set_my_admin_tag",{new_tag:clean});setMessage(error?error.message:"Owner tag saved.");}
 const stats=useMemo(()=>({accounts:users.length,suspended:users.filter(u=>Boolean(u.banned_until&&new Date(u.banned_until).getTime()>Date.now())).length,staff:users.filter(u=>u.staff_role).length,openReports:reports.filter(r=>r.status==="open").length}),[reports,users]);
 if(!ready)return<main className="tiger-v12-page"><div className="v12-loading-card">Checking staff access…</div></main>;
 const tabs:[Tab,string][]=[["accounts","Accounts"],["reports","Reports"],...(isOwner?[["roles","Roles"] as [Tab,string]]:[]),...(canAdmin?[["support","Support"] as [Tab,string]]:[]),...(isOwner?[["owner","Owner"] as [Tab,string]]:[])];
 return <main className="tiger-v12-page moderation-v12 v132-moderation"><header className="v12-page-header"><div><p className="v12-kicker">Staff console · {myRole}</p><h1>Moderation Center</h1><p>Moderation and role management with permission boundaries built in.</p></div><button className="secondary-button" onClick={()=>router.push("/chat")}>Back to chat</button></header>
 <section className="v12-stat-strip"><div><strong>{stats.accounts}</strong><span>Loaded accounts</span></div><div><strong>{stats.suspended}</strong><span>Suspended</span></div><div><strong>{stats.staff}</strong><span>Staff</span></div><div><strong>{stats.openReports}</strong><span>Open reports</span></div></section>
 <nav className="v12-segmented-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {(tab==="accounts"||tab==="roles")&&<section className="v12-panel"><div className="v12-panel-heading"><div><h2>{tab==="roles"?"Roles & badges":"Account management"}</h2><p>{tab==="roles"?"Only the Owner can promote staff or assign community badge roles.":"Review accounts and take actions allowed by your staff level."}</p></div></div><form className="v12-search-row" onSubmit={searchUsers}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, username, or email"/><button className="primary-button" disabled={loadingUsers}>{loadingUsers?"Searching…":"Search"}</button></form>
 <div className="v12-admin-table">{users.map(u=>{const banned=Boolean(u.banned_until&&new Date(u.banned_until).getTime()>Date.now());const staffProtected=u.staff_role==="owner"||(myRole==="moderator"&&Boolean(u.staff_role))||(myRole==="admin"&&u.staff_role==="admin");return <article className="v12-user-card v132-user-card" key={u.id}><div className="v12-user-identity"><span className="v12-avatar">{u.profile_emoji||"🐯"}</span><span><strong>{u.display_name}</strong><small>@{u.username} · {u.email||"No email"}</small><RoleBadges staffRole={u.staff_role} communityRoles={u.community_roles}/></span></div><div className="v12-pill-row">{u.supporter&&<span className="v12-pill supporter">⭐ {u.supporter_label}</span>}<span className={`v12-pill ${banned?"danger":"good"}`}>{banned?`Suspended · ${formatDate(u.banned_until)}`:"Active"}</span></div>
 {tab==="accounts"?<><div className="v12-user-meta"><span>Last sign-in<strong>{formatDate(u.last_sign_in_at)}</strong></span><span>Last active<strong>{formatDate(u.last_active_at)}</strong></span></div>{u.id!==userId&&<div className="v12-action-grid">{canAdmin&&!u.staff_role&&<button className={u.supporter?"secondary-button":"primary-button"} disabled={workingId===u.id} onClick={()=>void toggleSupporter(u)}>{u.supporter?"Remove supporter":"Grant supporter"}</button>}{!staffProtected&&(banned?<button className="secondary-button" disabled={workingId===u.id} onClick={()=>void setBan(u,"none")}>Restore account</button>:<><button className="secondary-button" disabled={workingId===u.id} onClick={()=>void setBan(u,"24h")}>Suspend 24h</button><button className="secondary-button" disabled={workingId===u.id} onClick={()=>void setBan(u,"168h")}>Suspend 7d</button>{canAdmin&&<button className="danger-button secondary-danger" disabled={workingId===u.id} onClick={()=>void setBan(u,"876000h")}>Ban</button>}</>)}</div>}</>:isOwner?<div className="v132-role-editor"><label>Staff access<select value={u.staff_role??"none"} disabled={u.staff_role==="owner"||u.id===userId||workingId===u.id} onChange={e=>void setStaffRole(u,e.target.value as "none"|"admin"|"moderator")}><option value="none">Member</option><option value="moderator">Moderator</option><option value="admin">Admin</option>{u.staff_role==="owner"&&<option value="owner">Owner</option>}</select></label><div className="v132-community-role-grid">{COMMUNITY_ROLE_OPTIONS.map(role=><button key={role.value} className={u.community_roles.includes(role.value)?"active":""} disabled={workingId===u.id} onClick={()=>void toggleCommunityRole(u,role.value)}><b>{role.icon}</b><span>{role.label}</span></button>)}</div></div>:null}</article>})}{!loadingUsers&&users.length===0&&<div className="v12-empty">No accounts matched your search.</div>}</div></section>}
 {tab==="reports"&&<section className="v12-panel"><div className="v12-panel-heading"><div><h2>Reports</h2><p>Moderators, admins, and the owner can review reports.</p></div><select value={reportFilter} onChange={e=>setReportFilter(e.target.value as typeof reportFilter)}><option value="open">Open</option><option value="all">All</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></div><div className="v12-report-list">{reports.map(r=><article className="v12-report-card" key={r.id}><div className="v12-report-top"><span className={`v12-pill ${r.status==="open"?"warning":"neutral"}`}>{r.status}</span><strong>{r.reason}</strong><time>{formatDate(r.created_at)}</time></div><p>{r.details||"No additional details were supplied."}</p><div className="v12-action-row">{r.status!=="dismissed"&&<button className="secondary-button" disabled={workingId===r.id} onClick={()=>void updateReport(r.id,"dismissed")}>Dismiss</button>}{r.status!=="resolved"&&<button className="primary-button" disabled={workingId===r.id} onClick={()=>void updateReport(r.id,"resolved")}>Resolve</button>}{r.status!=="open"&&<button className="secondary-button" disabled={workingId===r.id} onClick={()=>void updateReport(r.id,"open")}>Reopen</button>}</div></article>)}{!loadingReports&&reports.length===0&&<div className="v12-empty">No reports in this view.</div>}</div></section>}
 {tab==="support"&&canAdmin&&<section className="v12-panel"><div className="v12-panel-heading"><div><h2>Support operations</h2><p>Admins and the owner can manage supporter status and operating records.</p></div></div><AdminSupporterPanel userId={userId}/></section>}
 {tab==="owner"&&isOwner&&<section className="v12-panel"><div className="v12-panel-heading"><div><h2>Owner identity</h2><p>This badge is reserved for the Owner account.</p></div></div><label>Owner badge<input value={tag} onChange={e=>setTag(e.target.value)} maxLength={16}/></label><div className="v12-action-row"><span className="admin-badge-v7">{tag.trim()||"OWNER"}</span><button className="primary-button" onClick={()=>void saveTag()}>Save badge</button></div></section>}
 {message&&<div className="v12-toast" role="status">{message}</div>}</main>;
}
